---
- name: Install and Configure Tomcat on AWS EC2 (Ubuntu)
  hosts: localhost
  become: yes
  tasks:

    - name: Update package list
      apt:
        update_cache: yes

    - name: Install OpenJDK (required for Tomcat)
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Tomcat user
      user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false

    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-10/v10.1.14/bin/apache-tomcat-10.1.14.tar.gz"
        dest: /tmp/tomcat.tar.gz

    - name: Create Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Extract Tomcat
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Change ownership of Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Create a systemd service file for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/tomcat
          Environment=CATALINA_BASE=/opt/tomcat
          ExecStart=/opt/tomcat/bin/startup.sh
          ExecStop=/opt/tomcat/bin/shutdown.sh
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd and enable Tomcat service
      systemd:
        daemon_reload: yes
        name: tomcat
        enabled: yes
        state: started
