---
- name: Countdown Fun
  hosts: localhost
  connection: local

  tasks:
    - name: Countdown
      shell: "echo Countdown: {{ item }}"
      loop:
        - 5
        - 4
        - 3
        - 2
        - 1

    - name: Final Message
      debug:
        msg: "🚀 Boom! Ansible executed!"