---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        name: "Ansible1234"
        key_name: "Prit"
        instance_type: t2.micro
        image_id: ami-0e12ffc2dd465f6e4
        region: ap-south-1
        vpc_subnet_id: subnet-abc123
        assign_public_ip: true
        security_group: default
        count: 1
        wait: yes