---
- name: Install Nginx on AWS EC2 (Ubuntu)
  hosts: localhost
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
